### ISSUE TITLE
doubt about barcode pattern

### ISSUE THREAD

**Issue by PMoneda** [boombuler/barcode#25]
Hi, I tried to use twoofive barcode and I had some issues when reading barcode at banking mobile app So, I found in the code the following part
![capturar](https://user-images.githubusercontent.com/955433/30132347-723bfcc6-9326-11e7-8510-9c2ea54e4c67.PNG)
 
And there is a diference in the width. So I tried to change the interleaved option width to 3 and after that the mobile banking app started to read barcode faster. Why there is a diference between two options?

**Comment by boombuler** [comment]
Just googled a little and I can't tell why I set the value to `2` 3 years ago... but it seems like the acceptable range is 2.25:1 to 3:1. So changing the value to 3 seems like a good idea.
Would you mind making a pull-request? Otherwise it will take some time until I find some time to fix it.

Thanks for reporting!
