### ISSUE TITLE
How can we convert barcode to SVG image?

### ISSUE THREAD

**Issue by parthmind** [boombuler/barcode#57]
We are using this library to generate a code128 barcode image to display my order id in Jobticket, We are adding this image in HTML and then converting that HTML page into PDF to print it.

However the barcode image reads properly from image and HTML page through the mobile scanner and USB scanner both but when we convert the HTML Jobticket to PDF file, it does not scan unless we zoom it to high levels.

So We are planning if we can somehow generate SVG then it can not stretch or squash on the pdf file and can be read properly.

**Comment by boombuler** [comment]
I'm not familiar with any svg lib for go but I guess you can simply draw the lines of the barcode to an svg image. since code128 is a 1D barcode, the barcode will be generated as an image with X pixels width and one pixel height. where X is the number of bars. 

it should be easy with an lib like `https://github.com/ajstarks/svgo` if you need help with this, let me know. 

Hint for both of your questions: the barcode implements the [Image](https://golang.org/pkg/image/#Image) Interface from Golang

**Comment by huysentruitw** [comment]
@parthmind I have ported this library to C# and am supporting rendering to SVG (with an other library I have written but can be replaced by the one suggested by @boombuler ), it's not that much code, so probably it can be ported back to Golang 😅 

SVG Renderer: https://github.com/huysentruitw/barcoder/blob/master/src/Barcoder.Renderer.Svg/SvgRenderer.cs

SVG lib: https://github.com/huysentruitw/svglib/tree/master/src/SvgLib

**Comment by boombuler** [comment]
Sample for 1D Codes:
```golang
package main

import (
	"image/color"
	"os"

	svg "github.com/ajstarks/svgo"
	"github.com/boombuler/barcode/code128"
)

const height = 10

func main() {
	bc, err := code128.Encode("Foo")
	if err != nil {
		panic(err)
	}
	canvas := svg.New(os.Stdout)

	bounds := bc.Bounds()
	canvas.Start(bounds.Dx(), height)

	for x := bounds.Min.X; x < bounds.Max.X; x++ {
		if bc.At(x, bounds.Min.Y) == color.Black {
			start := x
			x++

			for x < bounds.Max.X && bc.At(x, bounds.Min.Y) == color.Black {
				x++
			}

			canvas.Rect(start, 0, x-start, height, "fill:black;stroke:black")
		}
	}

	canvas.End()
}

```
